name: "Parse and export variables"
description: "Parse .env / .yml / .yaml / .json / ADO yaml files to GitHub ENV"
author: your-name
inputs:
  files:
    description: "Comma-separated list of files to parse"
    required: true
    default: ""
  prefix:
    description: "Optional prefix for env vars"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Python
      shell: bash
      run: |
        python3 --version || sudo apt-get install -y python3 python3-pip
        pip3 install pyyaml

    - name: Run parser
      shell: bash
      run: python3 "${{ github.action_path }}/main.py"
      env:
        INPUT_FILES: ${{ inputs.files }}
        INPUT_PREFIX: ${{ inputs.prefix }}
